services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: database_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
